name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Git-Issues-Blog
      uses: Sep0lkit/git-issues-blog@release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
